# Malti Configuration File

[services]
# Define services that can send telemetry data

[services.auth-service]
api_key = "auth-service-key"
description = "Authentication service"

[services.payment-service]
api_key = "payment-service-key"
description = "Payment processing service"

[services.user-service]
api_key = "user-service-key"
description = "User management service"

[services.test-service]
api_key = "test-service-key"
description = "Test service"

[users]
# Define users who can query metrics and login to dashboard

[users.user1]
username = "user1"
api_key = "user-api-key"

[users.user2]
username = "user2"
api_key = "user2-api-key"

[api]
# API configuration (for test)
base_url = "http://localhost:8000"
ingest_endpoint = "/api/v1/ingest"
metrics_endpoint = "/api/v1/metrics"

[dashboard]
# Dashboard-specific configuration for visual indicators and thresholds
# These thresholds are used by the web dashboard to color-code metrics

[dashboard.thresholds]
# Error rate thresholds (in percentage) - used for coloring error rate displays
error_rate_success_threshold = 0.5     # Error rate <= 1% displays as green (success)
error_rate_warning_threshold = 1.0     # Error rate > 1% and <= 5% displays as yellow/orange (warning)
                                       # Error rate > 5% displays as red (error)

# Latency thresholds (in milliseconds) - used for coloring latency displays
latency_success_threshold = 300        # Latency <= 500ms displays as green (success)
latency_warning_threshold = 800       # Latency > 500ms and <= 1000ms displays as yellow/orange (warning)
                                       # Latency > 1000ms displays as red (error)
